name: matrix 
on: push

jobs: 
  node-version-job:
    runs-on: ubuntu-latest
    steps:
      - name: check default node version
        run: node -v 
      - name: run step on specific npm versions
        uses: actions/setup-node@v1
        with: 
            node-version: 6
      - name: check node version now
        run: node -v 