name: apitesting-workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - run: |
          node -v 
          npm -v
      - name: python commands 
        shell: python
        run: |
          import platform 
          print 
          (platform.processor())