name: apitesting-workflow

on: [push]

jobs:
  build-test-linux-shells:
    runs-on: ubuntu-latest
    steps:
      - name: string ni echo chesi chudham
        run: echo "hello world"
      - run: |
          node -v 
          npm -v
      - name: python shell use chesi commands run chedham
        shell: python
        run: |
          import platform 
          print 
          (platform.processor())
  build-test-winodws:
    runs-on: windows-latest
    needs: [build-test-linux-shells]
    steps:
      - name: powershell pwd chudham
        run: get-location
      - name: bash pwd chdham 
        shell: bash 
        run: pwd