name: mypractice-checkout-workflow 

on: [push]

jobs: 
  action-chuse-job:
     runs-on: [ubuntu-latest]
     steps: 
       - name: checkout branch
         uses: actions/checkout@v1
       - name: list files 
         run: |
          pwd
          ls -la
          echo "github reference branch"
          echo $GITHUB_REF
       - name: actions ela vadalo chudham
         id: naIDnaistam
         uses: actions/hello-world-javascript-action@v1
         with: 
           who-to-greet: "naku nene greetings....entira makidhi"
       - name: pina output chudalante pina step lo ID petti kinda dhanni json lo call cheyyi
         run: echo "${{ steps.naIDnaistam.outputs.time }}"